services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golden-tides
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-UTC}
    volumes:
      - ${DATA_PATH}/tides/:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge